# Enable C++ support
language: cpp
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
# Build steps
before_script:
  - ./build.sh
cache:
  directories:
  - wxwidgets-cache
before_cache:
  - cp -r wxwidgets wxwidgets-cache
script:
  - mkdir build
  - cd build
  - cmake .. && make
