# Enable C++ support
language: cpp
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
env:
  - APP=OFF EXAMPLE=OFF TESTS=OFF
  - APP=ON EXAMPLE=OFF TESTS=OFF
  - APP=ON EXAMPLE=ON TESTS=OFF
  - APP=ON EXAMPLE=OFF TESTS=ON
# Build steps
before_script:
  - sudo ./build.sh
cache:
  directories:
  - wxwidgets
script:
  - mkdir build
  - cd build
  - cmake .. -DEnableLightBulbApp=$APP -DEnableLightBulbExample=$EXAMPLE -DEnableUnitTests=$TESTS
  - make
  - cd ..
