# Enable C++ support
language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - ocl-icd-opencl-dev
    - gtk2.0
env:
  - APP=OFF EXAMPLE=OFF TESTS=OFF SHARED=OFF
  - APP=ON EXAMPLE=OFF TESTS=OFF SHARED=OFF
  - APP=ON EXAMPLE=ON TESTS=OFF SHARED=OFF
  - APP=ON EXAMPLE=OFF TESTS=ON SHARED=OFF
  - APP=OFF EXAMPLE=OFF TESTS=OFF SHARED=ON
  - APP=ON EXAMPLE=OFF TESTS=OFF SHARED=ON
  - APP=ON EXAMPLE=ON TESTS=OFF SHARED=ON
  - APP=ON EXAMPLE=OFF TESTS=ON SHARED=ON
# Build steps
before_script:
  - sudo ./build.sh
cache:
  directories:
  - wxwidgets
script:
  - mkdir build
  - cd build
  - cmake .. -DEnableLightBulbApp=$APP -DEnableLightBulbExample=$EXAMPLE -DEnableUnitTests=$TESTS -DBUILD_SHARED_LIBS=$SHARED
  - travis_wait 60 make -j 2
  - sudo make install
  - cd ..
