# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
before_script:
  - git clone https://github.com/wxWidgets/wxWidgets.git wxwidgets
  - cd wxwidgets
  - git reset --hard v3.1.0
  - mkdir build-gtk
  - cd build-gtk
  - ../configure --disable-shared --enable-unicode
  - make
  - sudo make install
  - cd ../..
script:
  - mkdir build
  - cd build
  - cmake .. && make
