# Enable C++ support
sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CXX=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: CC=clang++-3.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
# Build steps
before_script:
  - git clone https://github.com/wxWidgets/wxWidgets.git wxwidgets
  - cd wxwidgets
  - git reset --hard v3.1.0
  - mkdir build-gtk
  - cd build-gtk
  - ../configure --disable-shared --enable-unicode
  - make
  - sudo make install
  - cd ../..
script:
  - mkdir build
  - cd build
  - cmake .. && make
