# Enable C++ support
language: cpp
compiler:
  - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
# Build steps
before_script:
  - git clone https://github.com/wxWidgets/wxWidgets.git wxwidgets
  - cd wxwidgets
  - git reset --hard v3.1.0
  - mkdir build-gtk
  - cd build-gtk
  - ../configure --disable-shared --enable-unicode
  - make --silent
  - sudo make install
  - cd ../..
script:
  - mkdir build
  - cd build
  - cmake .. && make
